import { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence, useMotionValue, useTransform } from "framer-motion";
import { Link } from "react-router-dom";
import {
  ArrowRight,
  ChevronRight,
  Pill,
  Sparkles,
  Leaf,
  Layers,
  Award,
  Truck,
  CheckCircle,
  Mail,
  Phone,
  MapPin,
  Linkedin,
  Cpu,
  FlaskConical,
  FileCheck2,
} from "lucide-react";

// Import custom components
import PartnersMarquee from "@/components/sections/PartnersMarquee";

// Import custom industry HD images generated by AI
import pharmaImg from "@/assets/creative-pharma.png";
import cosmeticsImg from "@/assets/creative-cosmetics.png";
import foodImg from "@/assets/creative-food.png";
import legacyImg from "@/assets/creative-legacy.png";
import logoImg from "@/assets/logo.png";

const P = "#F69A1E"; // Brand color Orange/Amber

// 3D Card Tilt Wrapper for WOW effect
const TiltCard = ({ children, className, glowColor }) => {
  const x = useMotionValue(0);
  const y = useMotionValue(0);
  
  // Maps mouse position to degree rotation (-8 to 8 deg)
  const rotateX = useTransform(y, [-150, 150], [8, -8]);
  const rotateY = useTransform(x, [-150, 150], [-8, 8]);
  
  const handleMouseMove = (e: React.MouseEvent<HTMLDivElement>) => {
    const rect = e.currentTarget.getBoundingClientRect();
    const width = rect.width;
    const height = rect.height;
    // Calculate mouse position relative to card center
    const mouseX = e.clientX - rect.left - width / 2;
    const mouseY = e.clientY - rect.top - height / 2;
    x.set(mouseX);
    y.set(mouseY);
  };
  
  const handleMouseLeave = () => {
    x.set(0);
    y.set(0);
  };
  
  return (
    <motion.div
      onMouseMove={handleMouseMove}
      onMouseLeave={handleMouseLeave}
      style={{
        rotateX,
        rotateY,
        transformStyle: "preserve-3d",
        perspective: 1000,
      }}
      className={`transition-all duration-200 ${className}`}
    >
      <div 
        style={{ transform: "translateZ(30px)" }} 
        className="h-full w-full flex flex-col justify-between"
      >
        {children}
      </div>
    </motion.div>
  );
};

// Stats data
const STATS = [
  { value: "65+", label: "Years of Trust", desc: "Chemical Artistry" },
  { value: "400+", label: "Ingredients", desc: "Premium Catalog" },
  { value: "50+", label: "Global Partners", desc: "Exclusive Sourcing" },
  { value: "5", label: "Metro Hubs", desc: "Pan-India logistics" },
];

// Industry vertical details
const INDUSTRIES = [
  {
    id: "pharma",
    title: "Health & Well-being",
    subtitle: "Precision Bio-Delivery",
    desc: "Helping brands create high-performance supplements, clean vitamins, and life-enhancing health products using advanced bio-active solutions.",
    image: pharmaImg,
    glow: "rgba(246, 154, 30, 0.12)",
    borderColor: "rgba(246, 154, 30, 0.3)",
    textColor: "#DB8E00",
    icon: Pill,
    href: "/products?industry=pharma",
    products: ["Plant Binders", "Bio-Active Coatings", "Nutrient Carriers", "Advanced Bio-Deliveries"],
  },
  {
    id: "cosmetics",
    title: "Personal Care & Beauty",
    subtitle: "Clean Skin Innovation",
    desc: "Elevating skincare and luxury cosmetics with active botanical complexes, anti-aging peptides, and silky sensory textures that consumers love.",
    image: cosmeticsImg,
    glow: "rgba(219, 162, 55, 0.12)",
    borderColor: "rgba(219, 162, 55, 0.3)",
    textColor: "#C0841D",
    icon: Sparkles,
    href: "/products?industry=cosmetics",
    products: ["Barrier Ceramides", "Natural Glow Peptides", "Organic Botanical Oils", "Eco-Emulsifiers"],
  },
  {
    id: "food",
    title: "Food & Functional Nutrition",
    subtitle: "Taste Meets Wellness",
    desc: "Reimagining modern nutrition with plant-based prebiotic fibers, natural botanical sweeteners, and functional grains that keep foods delicious and healthy.",
    image: foodImg,
    glow: "rgba(252, 210, 1, 0.1)",
    borderColor: "rgba(252, 210, 1, 0.3)",
    textColor: "#B39500",
    icon: Leaf,
    href: "/products?industry=food",
    products: ["Prebiotic Chicory Fiber", "Clean Label Sweeteners", "Functional Pea Protein", "Natural Dietary Texturizers"],
  },
];

// Interactive Synthesizer Challenges
const SYNTHESIZER_DATA = [
  {
    id: "extended",
    challenge: "Continuous Ingredient Release",
    solution: "Methocel™ Premium HPMC",
    desc: "A pure cellulose-based polymer matrix designed to release active nutrients slowly and steadily over 24 hours, ensuring lasting efficacy and steady cellular absorption.",
    benefit: "Keeps beneficial nutrients active inside the body longer for maximum daily support.",
    techData: "Composition: Pure Plant Cellulose Matrix",
    principal: "DuPont Nutrition",
    icon: Pill,
  },
  {
    id: "solubility",
    challenge: "Instant Nutrient Solubility",
    solution: "Soluplus® Active Carrier",
    desc: "An advanced bio-carrier that encapsulates active ingredients to prevent clumping, allowing them to dissolve instantly in liquids and enter cells up to 10x faster.",
    benefit: "Enhances drink mixes and wellness shots for faster energy and vitamin delivery.",
    techData: "Composition: Bio-Friendly Polymeric Carrier",
    principal: "BASF Pharma Solutions",
    icon: Cpu,
  },
  {
    id: "barrier",
    challenge: "Vivid Skin Barrier Hydration",
    solution: "Phyto-Ceramide Lipids",
    desc: "A plant-derived multi-lamellar complex that perfectly mimics skin lipids. It locks in moisture, blocks external pollutants, and leaves skin looking smooth and luminous.",
    benefit: "Repairs dehydrated skin barriers, leaving a natural rose-gold glow.",
    techData: "Composition: Skin-Identical Lipid Complex",
    principal: "Vantage Specialty Ingredients",
    icon: Sparkles,
  },
  {
    id: "clean",
    challenge: "Guilt-Free Sugar Reduction",
    solution: "Fibrulose® Chicory Fiber",
    desc: "A 100% natural soluble fiber extracted from chicory roots. It replaces the texture of sugar and fat while enriching foods with prebiotics, allowing clean-label recipe formulations.",
    benefit: "Allows healthy sugar reduction with zero artificial aftertaste.",
    techData: "Composition: Chicory Root Extract Soluble Fiber",
    principal: "Cosucra Groupe",
    icon: Leaf,
  },
];

export default function CreativeHome() {
  const [activeSynth, setActiveSynth] = useState(SYNTHESIZER_DATA[0]);
  const [synthPulse, setSynthPulse] = useState(false);
  const [sampleForm, setSampleForm] = useState({ name: "", email: "", company: "", industry: "pharma", message: "" });
  const [formSubmitted, setFormSubmitted] = useState(false);
  const canvasRef = useRef<HTMLCanvasElement>(null);

  // Trigger brief animation pulse when changing synthesizer data
  const handleSynthChange = (item: typeof SYNTHESIZER_DATA[0]) => {
    setSynthPulse(true);
    setActiveSynth(item);
    setTimeout(() => setSynthPulse(false), 300);
  };

  // Canvas molecular animation for light background (floating pollen/sparks look)
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    let animationFrameId: number;
    let width = (canvas.width = window.innerWidth);
    let height = (canvas.height = window.innerHeight);

    const particles: Particle[] = [];
    const maxParticles = Math.min(50, Math.floor((width * height) / 30000));
    const connectionDist = 130;

    class Particle {
      x: number;
      y: number;
      vx: number;
      vy: number;
      radius: number;
      color: string;

      constructor() {
        this.x = Math.random() * width;
        this.y = Math.random() * height;
        this.vx = (Math.random() - 0.5) * 0.25;
        this.vy = (Math.random() - 0.5) * 0.25;
        this.radius = Math.random() * 2.5 + 1;
        this.color = Math.random() > 0.6 ? `rgba(246, 154, 30, ${Math.random() * 0.2 + 0.1})` : `rgba(100, 116, 139, ${Math.random() * 0.12 + 0.05})`;
      }

      update() {
        this.x += this.vx;
        this.y += this.vy;

        if (this.x < 0 || this.x > width) this.vx *= -1;
        if (this.y < 0 || this.y > height) this.vy *= -1;
      }

      draw(c: CanvasRenderingContext2D) {
        c.beginPath();
        c.arc(this.x, this.y, this.radius, 0, Math.PI * 2);
        c.fillStyle = this.color;
        c.fill();
      }
    }

    // Initialize particles
    for (let i = 0; i < maxParticles; i++) {
      particles.push(new Particle());
    }

    // Mouse interactive coordinates
    let mouse = { x: -9999, y: -9999 };
    const handleMouseMove = (e: MouseEvent) => {
      mouse.x = e.clientX;
      mouse.y = e.clientY;
    };
    const handleMouseLeave = () => {
      mouse.x = -9999;
      mouse.y = -9999;
    };

    window.addEventListener("mousemove", handleMouseMove);
    window.addEventListener("mouseleave", handleMouseLeave);

    const handleResize = () => {
      if (!canvas) return;
      width = canvas.width = window.innerWidth;
      height = canvas.height = window.innerHeight;
    };
    window.addEventListener("resize", handleResize);

    // Animation Loop
    const animate = () => {
      ctx.clearRect(0, 0, width, height);

      // Draw particle connections
      for (let i = 0; i < particles.length; i++) {
        const p1 = particles[i];
        p1.update();
        p1.draw(ctx);

        // Connect to mouse if close
        if (mouse.x !== -9999) {
          const dx = p1.x - mouse.x;
          const dy = p1.y - mouse.y;
          const dist = Math.sqrt(dx * dx + dy * dy);
          if (dist < 160) {
            ctx.beginPath();
            ctx.moveTo(p1.x, p1.y);
            ctx.lineTo(mouse.x, mouse.y);
            ctx.strokeStyle = `rgba(246, 154, 30, ${(1 - dist / 160) * 0.15})`;
            ctx.lineWidth = 0.8;
            ctx.stroke();
          }
        }

        for (let j = i + 1; j < particles.length; j++) {
          const p2 = particles[j];
          const dx = p1.x - p2.x;
          const dy = p1.y - p2.y;
          const dist = Math.sqrt(dx * dx + dy * dy);

          if (dist < connectionDist) {
            ctx.beginPath();
            ctx.moveTo(p1.x, p1.y);
            ctx.lineTo(p2.x, p2.y);
            const alpha = (1 - dist / connectionDist) * 0.12;
            ctx.strokeStyle = `rgba(246, 154, 30, ${alpha})`;
            ctx.lineWidth = 0.5;
            ctx.stroke();
          }
        }
      }

      animationFrameId = requestAnimationFrame(animate);
    };

    animate();

    return () => {
      cancelAnimationFrame(animationFrameId);
      window.removeEventListener("mousemove", handleMouseMove);
      window.removeEventListener("mouseleave", handleMouseLeave);
      window.removeEventListener("resize", handleResize);
    };
  }, []);

  const handleFormSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (sampleForm.name && sampleForm.email) {
      setFormSubmitted(true);
      setTimeout(() => {
        setFormSubmitted(false);
        setSampleForm({ name: "", email: "", company: "", industry: "pharma", message: "" });
      }, 5000);
    }
  };

  return (
    <div className="relative min-h-screen w-full overflow-hidden bg-[#FAF9F5] text-slate-800 selection:bg-amber-500/20 selection:text-amber-900">
      {/* 1. Interactive Canvas Background */}
      <canvas ref={canvasRef} className="pointer-events-none absolute inset-0 z-0 opacity-80" />

      {/* 2. Abstract Ambient Light Blobs */}
      <div className="absolute top-1/4 left-1/4 -z-10 h-[500px] w-[500px] rounded-full bg-amber-500/10 blur-[100px]" />
      <div className="absolute bottom-1/3 right-1/4 -z-10 h-[600px] w-[600px] rounded-full bg-indigo-500/5 blur-[120px]" />

      {/* 3. Custom Glass-morphic Header */}
      <header className="sticky top-0 z-50 w-full border-b border-slate-200/50 bg-white/70 backdrop-blur-md">
        <div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6 lg:px-8">
          <Link to="/" className="flex items-center gap-3">
            <img src={logoImg} alt="Scope" className="h-10 w-auto" />
            <div className="h-6 w-px bg-slate-200" />
            <span className="font-display text-xs font-bold uppercase tracking-[0.25em] text-slate-400">Nexus</span>
          </Link>

          <nav className="hidden items-center gap-8 md:flex">
            {["Legacy", "Industries", "Synthesizer", "Logistics", "Connect"].map((item) => (
              <a
                key={item}
                href={`#${item.toLowerCase()}`}
                className="font-display text-xs font-semibold uppercase tracking-wider text-slate-500 transition-colors hover:text-amber-600"
              >
                {item}
              </a>
            ))}
          </nav>

          <div className="flex items-center gap-4">
            <Link
              to="/products"
              className="hidden font-display text-xs font-semibold uppercase tracking-wider text-slate-500 hover:text-slate-900 sm:block"
            >
              Catalog
            </Link>
            <a
              href="#connect"
              className="inline-flex items-center justify-center rounded-full bg-slate-950 px-5 py-2.5 font-display text-xs font-bold uppercase tracking-wider text-white transition-all hover:bg-amber-500 hover:shadow-lg hover:shadow-amber-500/20 active:scale-95"
            >
              Order Sample
            </a>
          </div>
        </div>
      </header>

      {/* 4. Immersive Hero Section with Swirling Gold Video Background */}
      <section className="relative z-10 flex min-h-[calc(100vh-5rem)] items-center px-6 lg:px-8 overflow-hidden">
        {/* Background Swirling Liquid Gold Video Loop */}
        <video 
          autoPlay 
          loop 
          muted 
          playsInline 
          className="absolute inset-0 h-full w-full object-cover opacity-25 -z-20"
        >
          <source 
            src="https://assets.mixkit.co/videos/preview/mixkit-liquid-gold-swirling-background-30040-large.mp4" 
            type="video/mp4" 
          />
        </video>
        
        {/* Swirling Orange liquid alternate if preferred */}
        {/* <source src="https://assets.mixkit.co/videos/preview/mixkit-slow-motion-of-orange-liquid-background-40742-large.mp4" type="video/mp4" /> */}
        
        {/* Smooth overlay gradient to blend video into the light-cream background */}
        <div className="absolute inset-0 bg-gradient-to-b from-[#FAF9F5]/10 via-[#FAF9F5]/40 to-[#FAF9F5] -z-10" />

        <div className="mx-auto max-w-7xl py-12 lg:py-24">
          <div className="grid gap-16 lg:grid-cols-12 lg:items-center">
            {/* Hero Text */}
            <div className="lg:col-span-7">
              <motion.div
                initial={{ opacity: 0, y: 30 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8 }}
                className="inline-flex items-center gap-2 rounded-full border border-amber-500/20 bg-amber-500/10 px-4 py-1.5 font-display text-[10px] font-bold uppercase tracking-[0.2em] text-amber-700"
              >
                <Cpu className="h-3.5 w-3.5 animate-pulse text-amber-600" /> Elements of Inspiration
              </motion.div>

              <motion.h1
                initial={{ opacity: 0, y: 30 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8, delay: 0.1 }}
                className="mt-6 font-display text-4xl font-extrabold leading-[1.05] tracking-tight text-slate-900 sm:text-6xl xl:text-7.5xl"
              >
                Ingredients that Inspire. <br />
                <span className="bg-gradient-to-r from-amber-600 via-amber-500 to-yellow-600 bg-clip-text text-transparent">
                  Formulations that Wow.
                </span>
              </motion.h1>

              <motion.p
                initial={{ opacity: 0, y: 30 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8, delay: 0.2 }}
                className="mt-6 font-body text-base leading-relaxed text-slate-600 sm:text-lg max-w-[54ch]"
              >
                Welcome to the future of ingredient representation. We connect global scientific breakthroughs with premium local consumer brands, transforming raw active components into household names.
              </motion.p>

              <motion.div
                initial={{ opacity: 0, y: 30 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8, delay: 0.3 }}
                className="mt-10 flex flex-wrap gap-4"
              >
                <a
                  href="#industries"
                  className="group inline-flex items-center gap-2 rounded-full bg-amber-500 px-8 py-4 font-display text-sm font-bold text-white transition-all hover:bg-amber-600 hover:shadow-lg hover:shadow-amber-500/20 active:scale-95"
                >
                  Explore Verticals <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
                </a>
                <a
                  href="#legacy"
                  className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-8 py-4 font-display text-sm font-bold text-slate-700 transition-all hover:border-slate-300 hover:bg-slate-50 hover:text-slate-950"
                >
                  6 Decades of Excellence
                </a>
              </motion.div>
            </div>

            {/* Glowing Stats Dashboard Panel (Frosted Light Glass) */}
            <div className="lg:col-span-5 relative">
              <motion.div
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 1, delay: 0.2 }}
                className="relative rounded-3xl border border-white bg-white/70 p-8 backdrop-blur-xl shadow-[0_20px_50px_rgba(0,0,0,0.04)] overflow-hidden"
              >
                <div className="absolute top-0 right-0 h-40 w-40 bg-amber-500/5 rounded-full blur-3xl -z-10" />

                <div className="flex items-center gap-2 mb-8">
                  <div className="h-2 w-2 rounded-full bg-amber-500 animate-ping" />
                  <span className="font-display text-[10px] font-bold uppercase tracking-wider text-slate-400">Live Network Metrics</span>
                </div>

                <div className="grid grid-cols-2 gap-x-8 gap-y-10">
                  {STATS.map((stat, idx) => (
                    <motion.div
                      initial={{ opacity: 0, y: 15 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: 0.3 + idx * 0.1, duration: 0.5 }}
                      key={stat.label}
                    >
                      <p className="font-display text-4xl font-extrabold tracking-tight text-slate-950">
                        <span className="bg-gradient-to-r from-amber-600 to-amber-500 bg-clip-text text-transparent">
                          {stat.value}
                        </span>
                      </p>
                      <p className="mt-1 font-display text-xs font-semibold text-slate-800">{stat.label}</p>
                      <p className="font-body text-[10px] text-slate-500">{stat.desc}</p>
                    </motion.div>
                  ))}
                </div>
              </motion.div>
            </div>
          </div>
        </div>
      </section>

      {/* 5. Partners Logo Marquee Section */}
      <PartnersMarquee />

      {/* 6. Legacy Section - "6 Decades of Chemical Artistry" */}
      <section id="legacy" className="relative z-10 py-24 lg:py-36 px-6 lg:px-8 border-t border-slate-200/50">
        <div className="mx-auto max-w-7xl">
          <div className="grid gap-16 lg:grid-cols-12 lg:items-center">
            {/* Text Content */}
            <div className="lg:col-span-6">
              <span className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-slate-100 px-4 py-1.5 font-display text-[10px] font-bold uppercase tracking-[0.2em] text-slate-500">
                Legacy of Innovation
              </span>
              <h2 className="mt-6 font-display text-3xl font-extrabold tracking-tight text-slate-900 sm:text-5xl">
                6 Decades of <br />
                <span className="bg-gradient-to-r from-amber-600 to-amber-500 bg-clip-text text-transparent">
                  Chemical Artistry
                </span>
              </h2>
              <p className="mt-6 font-body text-base leading-relaxed text-slate-600">
                Since 1959, Scope has stood at the crossroads of science and beauty. We have spent over sixty years handpicking the world’s finest functional ingredients, enabling cosmetic houses, food creators, and wellness brands to construct products that define markets. 
              </p>
              <p className="mt-4 font-body text-base leading-relaxed text-slate-600">
                We believe chemical sourcing is not a trade; it is an art. It is about understanding how raw molecules mesh together to create products that deliver true consumer delight.
              </p>
              
              <div className="mt-8 flex gap-4">
                <Link
                  to="/about"
                  className="group inline-flex items-center gap-2 rounded-full bg-slate-900 px-6 py-3 font-display text-xs font-bold uppercase tracking-wider text-white transition-all hover:bg-amber-500"
                >
                  Our Full Story <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
                </Link>
              </div>
            </div>

            {/* Artistic AI-Generated 3D Legacy Image */}
            <div className="lg:col-span-6 flex justify-center">
              <motion.div 
                animate={{ y: [0, -12, 0] }}
                transition={{ duration: 6, repeat: Infinity, ease: "easeInOut" }}
                className="relative w-full max-w-[460px] aspect-square rounded-[3rem] overflow-hidden shadow-2xl border-4 border-white bg-white/50 backdrop-blur-md"
              >
                <img 
                  src={legacyImg} 
                  alt="6 Decades of Scientific Sculpture" 
                  className="h-full w-full object-cover"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-slate-900/10 via-transparent to-transparent" />
                <div className="absolute bottom-6 left-6 right-6 rounded-2xl bg-white/90 p-5 backdrop-blur-md border border-slate-100 shadow-lg text-center">
                  <p className="font-display text-lg font-bold text-slate-900">Est. 1959</p>
                  <p className="font-body text-[11px] text-slate-500">Transforming ingredients into iconic brands</p>
                </div>
              </motion.div>
            </div>
          </div>
        </div>
      </section>

      {/* 7. Bento Grid / Industry Vertical Selector (Vivid B2C Focus + 3D Tilt) */}
      <section id="industries" className="relative z-10 py-24 lg:py-36 px-6 lg:px-8 border-t border-slate-200/50 bg-slate-100/30">
        <div className="mx-auto max-w-7xl">
          <div className="text-center">
            <span className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-slate-100 px-4 py-1.5 font-display text-[10px] font-bold uppercase tracking-[0.2em] text-slate-500">
              Our Verticals
            </span>
            <h2 className="mt-4 font-display text-3xl font-extrabold tracking-tight text-slate-900 sm:text-5xl">
              Three Verticals.{" "}
              <span className="bg-gradient-to-r from-amber-600 to-amber-500 bg-clip-text text-transparent">
                Infinite Possibilities.
              </span>
            </h2>
            <p className="mx-auto mt-4 max-w-2xl font-body text-sm text-slate-500">
              We curate pure active components that drive formulation breakthroughs, delivering wellness, sensory appeal, and taste.
            </p>
          </div>

          <div className="mt-16 grid gap-8 lg:grid-cols-3">
            {INDUSTRIES.map((ind) => {
              const Icon = ind.icon;
              return (
                <TiltCard
                  key={ind.id}
                  className="group relative flex flex-col justify-between overflow-hidden rounded-[2rem] border border-slate-200 bg-white/80 p-6 backdrop-blur-md transition-all hover:bg-white shadow-[0_10px_35px_rgba(0,0,0,0.02)] hover:shadow-[0_25px_60px_rgba(246,154,30,0.08)] cursor-pointer min-h-[500px]"
                  glowColor={ind.glow}
                >
                  <div>
                    {/* Visual Image container */}
                    <div className="relative aspect-[4/3] w-full overflow-hidden rounded-2xl border border-slate-100">
                      <img
                        src={ind.image}
                        alt={ind.title}
                        className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-108"
                      />
                      <div className="absolute inset-0 bg-gradient-to-t from-slate-900 via-slate-900/10 to-transparent opacity-60" />
                      <div className="absolute bottom-4 left-4 flex items-center gap-2">
                        <div
                          className="flex h-8 w-8 items-center justify-center rounded-lg bg-white/90 text-slate-950"
                          style={{ border: `1px solid ${ind.borderColor}` }}
                        >
                          <Icon className="h-4 w-4" style={{ color: ind.textColor }} />
                        </div>
                        <span className="font-display text-[10px] font-bold uppercase tracking-widest text-white">
                          {ind.subtitle}
                        </span>
                      </div>
                    </div>

                    <h3 className="mt-6 font-display text-2xl font-bold text-slate-900 group-hover:text-amber-600 transition-colors">
                      {ind.title}
                    </h3>
                    <p className="mt-3 font-body text-sm leading-relaxed text-slate-500">
                      {ind.desc}
                    </p>

                    {/* Product Pills list */}
                    <div className="mt-6 flex flex-wrap gap-2">
                      {ind.products.map((p) => (
                        <span
                          key={p}
                          className="rounded-full bg-slate-50 border border-slate-100 px-3.5 py-1.5 font-body text-[11px] font-medium text-slate-600"
                        >
                          {p}
                        </span>
                      ))}
                    </div>
                  </div>

                  <div className="mt-8 pt-4 border-t border-slate-100 flex items-center justify-between">
                    <Link
                      to={ind.href}
                      className="inline-flex items-center gap-2 font-display text-xs font-bold uppercase tracking-wider text-slate-500 group-hover:text-slate-900 transition-colors"
                    >
                      Browse ingredients <ArrowRight className="h-3.5 w-3.5 group-hover:translate-x-1 transition-transform" style={{ color: ind.textColor }} />
                    </Link>
                  </div>
                </TiltCard>
              );
            })}
          </div>
        </div>
      </section>

      {/* 8. Interactive Excipient Selector (Interactive Mini-App) */}
      <section id="synthesizer" className="relative z-10 py-24 lg:py-36 px-6 lg:px-8 border-t border-slate-200/50 bg-white">
        <div className="mx-auto max-w-7xl">
          <div className="text-center">
            <span className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-slate-100 px-4 py-1.5 font-display text-[10px] font-bold uppercase tracking-[0.2em] text-slate-500">
              Interactive Lab Widget
            </span>
            <h2 className="mt-4 font-display text-3xl font-extrabold tracking-tight text-slate-900 sm:text-5xl">
              Interactive{" "}
              <span className="bg-gradient-to-r from-amber-600 to-amber-500 bg-clip-text text-transparent">
                Excipient Selector
              </span>
            </h2>
            <p className="mx-auto mt-4 max-w-2xl font-body text-sm text-slate-500">
              Select a formulation challenge to see the corresponding structural polymer solution, biochemical properties, and manufacturers.
            </p>
          </div>

          <div className="mt-16 grid gap-10 lg:grid-cols-12">
            {/* Left challenges tabs selector */}
            <div className="lg:col-span-5 flex flex-col gap-4">
              {SYNTHESIZER_DATA.map((item) => {
                const ItemIcon = item.icon;
                const isSelected = activeSynth.id === item.id;
                return (
                  <button
                    key={item.id}
                    onClick={() => handleSynthChange(item)}
                    className={`flex items-center gap-4 rounded-2xl p-5 text-left border transition-all duration-300 ${
                      isSelected
                        ? "border-amber-500/30 bg-amber-500/10 shadow-sm"
                        : "border-slate-200/60 bg-white/60 hover:border-slate-300 hover:bg-white"
                    }`}
                  >
                    <div
                      className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl transition-colors ${
                        isSelected ? "bg-amber-500 text-white" : "bg-slate-100 text-slate-500"
                      }`}
                    >
                      <ItemIcon className="h-5 w-5" />
                    </div>
                    <div>
                      <p className={`font-display text-sm font-bold ${isSelected ? "text-slate-950" : "text-slate-800"}`}>
                        {item.challenge}
                      </p>
                      <p className="mt-0.5 font-body text-[11px] text-slate-500">Solution: {item.solution}</p>
                    </div>
                    <ChevronRight
                      className={`ml-auto h-4 w-4 shrink-0 transition-transform ${
                        isSelected ? "translate-x-1 text-amber-600" : "text-slate-400"
                      }`}
                    />
                  </button>
                );
              })}
            </div>

            {/* Right solution reactor container */}
            <div className="lg:col-span-7">
              <div className="relative h-full rounded-3xl border border-slate-200 bg-slate-50/70 p-8 backdrop-blur-xl shadow-sm overflow-hidden flex flex-col justify-between min-h-[420px]">
                {/* Decorative glow panel inside reactor */}
                <div className="absolute -right-20 -top-20 h-60 w-60 bg-amber-500/5 rounded-full blur-[80px]" />
                
                {/* Synthesizer Animation Wrapper */}
                <AnimatePresence mode="wait">
                  <motion.div
                    key={activeSynth.id}
                    initial={{ opacity: 0, x: 20 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: -20 }}
                    transition={{ duration: 0.25 }}
                    className="flex-1 flex flex-col justify-between"
                  >
                    <div>
                      {/* Active Synth Header */}
                      <div className="flex items-center justify-between pb-6 border-b border-slate-200">
                        <div>
                          <span className="font-display text-[9px] font-bold uppercase tracking-widest text-slate-400">
                            Partner Manufacturer: {activeSynth.principal}
                          </span>
                          <h4 className="mt-1 font-display text-2xl font-extrabold text-slate-900">
                            {activeSynth.solution}
                          </h4>
                        </div>
                        <div className="rounded-xl border border-amber-500/20 bg-amber-500/10 px-3 py-1.5 text-center">
                          <span className="font-display text-[10px] font-bold uppercase tracking-wider text-amber-700">
                            Active Spec
                          </span>
                        </div>
                      </div>

                      {/* Content details */}
                      <div className="mt-8 space-y-6">
                        <div>
                          <h5 className="font-display text-xs font-bold uppercase tracking-wider text-slate-500">
                            Mechanistic Description
                          </h5>
                          <p className="mt-2 font-body text-sm leading-relaxed text-slate-600 font-medium">
                            {activeSynth.desc}
                          </p>
                        </div>

                        <div className="grid sm:grid-cols-2 gap-6">
                          <div>
                            <h5 className="font-display text-xs font-bold uppercase tracking-wider text-slate-500">
                              Clinical/Functional Benefit
                            </h5>
                            <p className="mt-1.5 font-body text-xs text-slate-600 leading-relaxed">
                              {activeSynth.benefit}
                            </p>
                          </div>
                          <div>
                            <h5 className="font-display text-xs font-bold uppercase tracking-wider text-slate-500">
                              Technical Parameters
                            </h5>
                            <code className="mt-2 block rounded-lg bg-white border border-slate-200 p-2 font-mono text-[10px] text-amber-700">
                              {activeSynth.techData}
                            </code>
                          </div>
                        </div>
                      </div>
                    </div>

                    {/* Action buttons */}
                    <div className="mt-8 pt-6 border-t border-slate-200 flex flex-wrap gap-4 items-center justify-between">
                      <span className="text-[11px] font-body text-slate-400 italic">
                        Formulation support & data sheets available.
                      </span>
                      <a
                        href="#connect"
                        className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-2.5 font-display text-xs font-bold uppercase tracking-wider text-white transition-colors hover:bg-amber-500"
                      >
                        Request Sample <ChevronRight className="h-4 w-4" />
                      </a>
                    </div>
                  </motion.div>
                </AnimatePresence>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 9. Animated Supply Network Map Section */}
      <section id="logistics" className="relative z-10 py-24 lg:py-36 px-6 lg:px-8 border-t border-slate-200/50">
        <div className="mx-auto max-w-7xl">
          <div className="grid gap-16 lg:grid-cols-12 lg:items-center">
            {/* Text description */}
            <div className="lg:col-span-5">
              <span className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-slate-100 px-4 py-1.5 font-display text-[10px] font-bold uppercase tracking-[0.2em] text-slate-500">
                Logistics & Reach
              </span>
              <h2 className="mt-4 font-display text-3xl font-extrabold tracking-tight text-slate-900 sm:text-5xl">
                Global Sourcing. <br />
                <span className="bg-gradient-to-r from-amber-600 to-amber-500 bg-clip-text text-transparent">
                  Local Distribution.
                </span>
              </h2>
              <p className="mt-6 font-body text-sm leading-relaxed text-slate-500">
                We bridge international suppliers with Indian manufacturers. Our network channels active ingredients from production units in Europe, USA, Japan, and Korea directly to domestic warehouses and R&D centers.
              </p>

              <div className="mt-10 space-y-6">
                {[
                  { title: "Metro Hub Warehouses", desc: "Temperature-controlled storage centers in Chennai, Mumbai, Delhi, Hyderabad, and Bangalore." },
                  { title: "Assured Cold Chains", desc: "Monitored supply chain logistics maintaining optimal storage parameters for sensitive biologics and actives." },
                  { title: "Regulatory Approvals", desc: "Fully-equipped documentation offices facilitating swift custom clearances and compliance audits." },
                ].map((item) => (
                  <div key={item.title} className="flex gap-4 items-start">
                    <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg border border-amber-500/25 bg-amber-500/5 text-amber-600 mt-0.5">
                      <Truck className="h-3.5 w-3.5" />
                    </div>
                    <div>
                      <h4 className="font-display text-sm font-bold text-slate-900">{item.title}</h4>
                      <p className="mt-1 font-body text-xs text-slate-500">{item.desc}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Glowing SVG Map Representation */}
            <div className="lg:col-span-7 flex justify-center">
              <div className="relative w-full max-w-[600px] aspect-[4/3] rounded-3xl border border-slate-200 bg-white/80 p-4 backdrop-blur-md overflow-hidden shadow-sm">
                {/* SVG Schematic map of India with connectivity rays */}
                <svg viewBox="0 0 600 450" className="w-full h-full opacity-90" xmlns="http://www.w3.org/2000/svg">
                  <defs>
                    <pattern id="grid-light" width="20" height="20" patternUnits="userSpaceOnUse">
                      <path d="M 20 0 L 0 0 0 20" fill="none" stroke="rgba(0, 0, 0, 0.02)" strokeWidth="1" />
                    </pattern>
                  </defs>
                  <rect width="100%" height="100%" fill="url(#grid-light)" />

                  {/* Nodes for international locations */}
                  <circle cx="50" cy="100" r="4" fill="#94a3b8" />
                  <text x="50" y="88" fill="#94a3b8" fontSize="8" fontFamily="Sora" textAnchor="middle">USA SOURCING</text>

                  <circle cx="80" cy="220" r="4" fill="#94a3b8" />
                  <text x="80" y="208" fill="#94a3b8" fontSize="8" fontFamily="Sora" textAnchor="middle">EUROPE SOURCING</text>

                  <circle cx="540" cy="120" r="4" fill="#94a3b8" />
                  <text x="540" y="108" fill="#94a3b8" fontSize="8" fontFamily="Sora" textAnchor="middle">JAPAN/KOREA</text>

                  {/* Major Indian Cities */}
                  <g id="indian-nodes">
                    {/* Delhi */}
                    <circle cx="320" cy="180" r="6" fill="#F69A1E" className="animate-ping" style={{ transformOrigin: "320px 180px", animationDuration: "3s" }} />
                    <circle cx="320" cy="180" r="4.5" fill="#F69A1E" />
                    <text x="320" y="170" fill="#1e293b" fontSize="10" fontWeight="bold" fontFamily="Sora" textAnchor="middle">DELHI</text>

                    {/* Mumbai */}
                    <circle cx="270" cy="280" r="6" fill="#F69A1E" className="animate-ping" style={{ transformOrigin: "270px 280px", animationDuration: "3s", animationDelay: "0.5s" }} />
                    <circle cx="270" cy="280" r="4.5" fill="#F69A1E" />
                    <text x="250" y="284" fill="#1e293b" fontSize="10" fontWeight="bold" fontFamily="Sora" textAnchor="end">MUMBAI</text>

                    {/* Hyderabad */}
                    <circle cx="330" cy="300" r="6" fill="#F69A1E" className="animate-ping" style={{ transformOrigin: "330px 300px", animationDuration: "3s", animationDelay: "1s" }} />
                    <circle cx="330" cy="300" r="4.5" fill="#F69A1E" />
                    <text x="345" y="304" fill="#1e293b" fontSize="10" fontWeight="bold" fontFamily="Sora" textAnchor="start">HYDERABAD</text>

                    {/* Bangalore */}
                    <circle cx="310" cy="350" r="6" fill="#F69A1E" className="animate-ping" style={{ transformOrigin: "310px 350px", animationDuration: "3s", animationDelay: "1.5s" }} />
                    <circle cx="310" cy="350" r="4.5" fill="#F69A1E" />
                    <text x="290" y="354" fill="#1e293b" fontSize="10" fontWeight="bold" fontFamily="Sora" textAnchor="end">BANGALORE</text>

                    {/* Chennai */}
                    <circle cx="340" cy="360" r="6" fill="#F69A1E" className="animate-ping" style={{ transformOrigin: "340px 360px", animationDuration: "3s", animationDelay: "2s" }} />
                    <circle cx="340" cy="360" r="4.5" fill="#F69A1E" />
                    <text x="355" y="364" fill="#1e293b" fontSize="10" fontWeight="bold" fontFamily="Sora" textAnchor="start">CHENNAI (HQ)</text>
                  </g>

                  {/* domestic connections */}
                  <g stroke="#F69A1E" strokeWidth="1.5" fill="none" opacity="0.45">
                    <path d="M 50 100 Q 150 150, 270 280" strokeDasharray="6,4" className="animate-marquee-left" style={{ animationDuration: "12s" }} />
                    <path d="M 80 220 Q 180 240, 270 280" strokeDasharray="6,4" className="animate-marquee-left" style={{ animationDuration: "10s" }} />
                    <path d="M 540 120 Q 450 250, 340 360" strokeDasharray="6,4" className="animate-marquee-left" style={{ animationDuration: "11s" }} />

                    <path d="M 340 360 L 310 350" stroke="#cbd5e1" strokeWidth="1" strokeDasharray="3,3" />
                    <path d="M 310 350 L 270 280" stroke="#cbd5e1" strokeWidth="1" strokeDasharray="3,3" />
                    <path d="M 270 280 L 330 300" stroke="#cbd5e1" strokeWidth="1" strokeDasharray="3,3" />
                    <path d="M 330 300 L 320 180" stroke="#cbd5e1" strokeWidth="1" strokeDasharray="3,3" />
                    <path d="M 340 360 L 330 300" stroke="#cbd5e1" strokeWidth="1" strokeDasharray="3,3" />
                  </g>
                </svg>

                <div className="absolute bottom-6 left-6 right-6 flex items-center justify-between text-[10px] font-body text-slate-400 border-t border-slate-100 pt-4">
                  <span>✦ Connecting 50+ Global Manufacturers</span>
                  <span>Direct Delivery Pan-India ✦</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 10. Technical Support Capabilities Dashboard */}
      <section id="services" className="relative z-10 py-24 lg:py-36 px-6 lg:px-8 border-t border-slate-200/50 bg-[#FAF9F5]/45">
        <div className="mx-auto max-w-7xl">
          <div className="text-center">
            <span className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-slate-100 px-4 py-1.5 font-display text-[10px] font-bold uppercase tracking-[0.2em] text-slate-500">
              Technical Support
            </span>
            <h2 className="mt-4 font-display text-3xl font-extrabold tracking-tight text-slate-900 sm:text-5xl">
              Scientific Support.{" "}
              <span className="bg-gradient-to-r from-amber-600 to-amber-500 bg-clip-text text-transparent">
                Beyond Supply.
              </span>
            </h2>
            <p className="mx-auto mt-4 max-w-2xl font-body text-sm text-slate-500">
              We offer direct access to formulation scientists, regulatory assistance, and compliance documentation.
            </p>
          </div>

          <div className="mt-16 grid gap-8 md:grid-cols-2 lg:grid-cols-4">
            {[
              { icon: FlaskConical, title: "Application Lab Support", desc: "Formulation assistance, pilot batch optimization, and stability analysis for custom product developments." },
              { icon: FileCheck2, title: "Regulatory Documentation", desc: "Fast declarations, technical audits, material analysis certifications, and documentation guidance." },
              { icon: Layers, title: "Curated Excipient Range", desc: "Over 400+ distinct functional ingredients selected to solve sensory, binding, or stability issues." },
              { icon: Award, title: "Quality Assurance", desc: "Optimal temperature-controlled storage, clean warehouse practices, and reliable ingredient logistics." },
            ].map((serv, index) => {
              const ServIcon = serv.icon;
              return (
                <motion.div
                  key={serv.title}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: index * 0.1, duration: 0.6 }}
                  className="rounded-3xl border border-slate-200 bg-white/80 p-6 hover:border-amber-500/20 hover:bg-white hover:shadow-sm transition-all group"
                >
                  <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-slate-50 text-amber-600 mb-6 group-hover:bg-slate-950 group-hover:text-white transition-colors">
                    <ServIcon className="h-5 w-5" />
                  </div>
                  <h3 className="font-display text-base font-bold text-slate-900 group-hover:text-amber-600 transition-colors">
                    {serv.title}
                  </h3>
                  <p className="mt-3 font-body text-xs leading-relaxed text-slate-500">
                    {serv.desc}
                  </p>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* 11. Immersive Luminous CTA / Sample Form */}
      <section id="connect" className="relative z-10 py-24 lg:py-36 px-6 lg:px-8 border-t border-slate-200/50">
        <div className="mx-auto max-w-5xl">
          <div className="relative rounded-[2.5rem] border border-amber-500/20 bg-white/90 p-8 sm:p-12 lg:p-16 backdrop-blur-xl overflow-hidden shadow-[0_30px_70px_rgba(246,154,30,0.05)]">
            {/* Glow blob */}
            <div className="absolute -left-20 -bottom-20 h-60 w-60 bg-amber-500/5 rounded-full blur-[80px]" />

            <div className="grid gap-12 lg:grid-cols-12 items-center">
              {/* Form details left */}
              <div className="lg:col-span-5">
                <span className="font-display text-[10px] font-bold uppercase tracking-[0.2em] text-amber-600">
                  Formulation Material Requests
                </span>
                <h3 className="mt-4 font-display text-3xl font-extrabold text-slate-900 leading-tight">
                  Accelerate Your <br />
                  <span className="bg-gradient-to-r from-amber-600 to-amber-500 bg-clip-text text-transparent">
                    Formulation R&D
                  </span>
                </h3>
                <p className="mt-4 font-body text-xs leading-relaxed text-slate-500">
                  Request active ingredient samples and technical data sheets. Our logistics team dispatches samples within 48 hours across India.
                </p>

                <div className="mt-8 space-y-4 text-xs font-body text-slate-500">
                  <div className="flex items-center gap-3">
                    <MapPin className="h-4 w-4 text-amber-600" />
                    <span>Egmore, Chennai, India</span>
                  </div>
                  <div className="flex items-center gap-3">
                    <Mail className="h-4 w-4 text-amber-600" />
                    <span>sales@scope-india.com</span>
                  </div>
                  <div className="flex items-center gap-3">
                    <Phone className="h-4 w-4 text-amber-600" />
                    <span>+91 44 40 400 400</span>
                  </div>
                </div>
              </div>

              {/* Sample Request Form right */}
              <div className="lg:col-span-7">
                {formSubmitted ? (
                  <motion.div
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    className="flex flex-col items-center justify-center py-12 text-center"
                  >
                    <div className="flex h-12 w-12 items-center justify-center rounded-full bg-amber-500 text-white mb-4 shadow-md">
                      <CheckCircle className="h-6 w-6" />
                    </div>
                    <h4 className="font-display text-xl font-bold text-slate-900">Sample Request Lodged</h4>
                    <p className="mt-2 font-body text-xs text-slate-500 max-w-[34ch]">
                      Thank you. A scientific representative will contact you shortly to verify batch and dispatch specifications.
                    </p>
                  </motion.div>
                ) : (
                  <form onSubmit={handleFormSubmit} className="space-y-4">
                    <div className="grid sm:grid-cols-2 gap-4">
                      <div>
                        <label className="block font-display text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-1">
                          Full Name
                        </label>
                        <input
                          required
                          type="text"
                          value={sampleForm.name}
                          onChange={(e) => setSampleForm({ ...sampleForm, name: e.target.value })}
                          placeholder="Dr. Shreyas"
                          className="w-full rounded-xl border border-slate-200 bg-white p-3 font-body text-xs text-slate-800 placeholder:text-slate-300 focus:border-amber-500 focus:outline-none focus:ring-1 focus:ring-amber-500/30"
                        />
                      </div>
                      <div>
                        <label className="block font-display text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-1">
                          Corporate Email
                        </label>
                        <input
                          required
                          type="email"
                          value={sampleForm.email}
                          onChange={(e) => setSampleForm({ ...sampleForm, email: e.target.value })}
                          placeholder="name@company.com"
                          className="w-full rounded-xl border border-slate-200 bg-white p-3 font-body text-xs text-slate-800 placeholder:text-slate-300 focus:border-amber-500 focus:outline-none focus:ring-1 focus:ring-amber-500/30"
                        />
                      </div>
                    </div>

                    <div className="grid sm:grid-cols-2 gap-4">
                      <div>
                        <label className="block font-display text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-1">
                          Company Name
                        </label>
                        <input
                          type="text"
                          value={sampleForm.company}
                          onChange={(e) => setSampleForm({ ...sampleForm, company: e.target.value })}
                          placeholder="e.g. Scope Labs"
                          className="w-full rounded-xl border border-slate-200 bg-white p-3 font-body text-xs text-slate-800 placeholder:text-slate-300 focus:border-amber-500 focus:outline-none focus:ring-1 focus:ring-amber-500/30"
                        />
                      </div>
                      <div>
                        <label className="block font-display text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-1">
                          Industry Sector
                        </label>
                        <select
                          value={sampleForm.industry}
                          onChange={(e) => setSampleForm({ ...sampleForm, industry: e.target.value })}
                          className="w-full rounded-xl border border-slate-200 bg-white p-3 font-body text-xs text-slate-800 focus:border-amber-500 focus:outline-none focus:ring-1 focus:ring-amber-500/30"
                        >
                          <option value="pharma">Pharmaceuticals</option>
                          <option value="cosmetics">Cosmetics & Derma</option>
                          <option value="food">Food & Nutraceuticals</option>
                        </select>
                      </div>
                    </div>

                    <div>
                      <label className="block font-display text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-1">
                        Formulation Details / Target Spec
                      </label>
                      <textarea
                        rows={3}
                        value={sampleForm.message}
                        onChange={(e) => setSampleForm({ ...sampleForm, message: e.target.value })}
                        placeholder="Please detail the ingredients required or formulation issue you're solving..."
                        className="w-full rounded-xl border border-slate-200 bg-white p-3 font-body text-xs text-slate-800 placeholder:text-slate-300 focus:border-amber-500 focus:outline-none focus:ring-1 focus:ring-amber-500/30"
                      />
                    </div>

                    <button
                      type="submit"
                      className="w-full rounded-xl bg-amber-500 p-4 font-display text-xs font-bold uppercase tracking-wider text-white transition-all hover:bg-amber-600 hover:shadow-lg hover:shadow-amber-500/20 active:scale-[0.98]"
                    >
                      Submit Technical Request
                    </button>
                  </form>
                )}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 12. Sleek Minimal Footer */}
      <footer className="relative z-10 border-t border-slate-100 py-12 px-6 lg:px-8 bg-[#FAF9F5]">
        <div className="mx-auto max-w-7xl flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="flex items-center gap-3">
            <img src={logoImg} alt="Scope" className="h-8 w-auto" />
            <div className="h-4 w-px bg-slate-200" />
            <span className="font-display text-[10px] text-slate-400 tracking-wider">© 2026 Scope Ingredients. All Rights Reserved.</span>
          </div>

          <div className="flex items-center gap-6">
            <Link to="/" className="font-display text-xs text-slate-500 hover:text-slate-850 transition-colors">
              Corporate Standard Site
            </Link>
            <div className="h-4 w-px bg-slate-200" />
            <a
              href="https://linkedin.com"
              target="_blank"
              rel="noreferrer"
              className="text-slate-400 hover:text-slate-700 transition-colors"
            >
              <Linkedin className="h-4 w-4" />
            </a>
          </div>
        </div>
      </footer>
    </div>
  );
}
